In [20]:
import torch.nn as nn
import torch
m = nn.Linear(3, 5)

In [21]:
input = torch.randn(10,3)
input

tensor([[ 0.2562,  0.1317, -0.6589],
        [-1.0391, -0.4555, -1.1375],
        [-0.5660,  0.3490,  0.4192],
        [ 1.1308, -1.2806,  1.1526],
        [ 0.1411,  1.4243, -0.8320],
        [-0.7661, -0.3592,  1.6762],
        [-0.8154,  0.0034, -1.2402],
        [-0.1616,  0.3790,  1.8003],
        [ 0.1366,  0.2582, -1.2251],
        [ 0.9389, -0.3511,  0.8199]])

In [22]:
m(input)

tensor([[ 0.0312, -0.4003, -0.3258,  0.3520,  0.1920],
        [ 1.0519, -0.0433, -0.4476,  0.1996,  0.2021],
        [ 0.0837, -0.0205, -0.1996, -0.2507,  0.0655],
        [-0.0384, -0.6441,  0.2541, -0.0887, -1.0920],
        [-0.5442, -0.2870, -0.5155,  0.3856,  0.8552],
        [ 0.2795,  0.1009,  0.1128, -0.7610, -0.6110],
        [ 0.7303, -0.0955, -0.5037,  0.2936,  0.4208],
        [-0.4154, -0.0420,  0.0973, -0.6537, -0.3712],
        [ 0.1422, -0.3975, -0.4600,  0.5289,  0.4303],
        [-0.3564, -0.5428,  0.0690, -0.0160, -0.5419]],
       grad_fn=<AddmmBackward>)

In [29]:
rand_noise = torch.rand(size = (3,3))
rand_noise

tensor([[0.8749, 0.7416, 0.3566],
        [0.1968, 0.8250, 0.6864],
        [0.7481, 0.3506, 0.3016]])

In [33]:
from torch.autograd import Variable
normal_rand_noise = Variable(rand_noise.normal_(mean= 0 , std = 1),requires_grad=False).cuda()
normal_rand_noise

tensor([[-0.7607, -1.0012, -0.2644],
        [ 0.2550, -0.6453,  1.7756],
        [ 1.3425,  2.1105,  0.0536]], device='cuda:0')